### ISSUE TITLE
If folder does not exist on a platform then it errors

### ISSUE THREAD

**Issue by niftylettuce** [vutran/os-fonts#5]
I believe that if we pass `useType` to be `network`, and the path does not exist for the network folder, then we should return an empty array instead of throwing an error (because `path.join` and `fs.readDir` are reading a director that does not exist.  Perhaps you could modify the code so that it checks `fs.stats` if the directory exists, and if not return an empty array.

**Comment by vutran** [comment]
This should be fixed in this patch [here](https://github.com/vutran/os-fonts/commit/2d7251d2fd954241813d2c7c8e8e64c88994a73b#diff-168726dbe96b3ce427e7fedce31bb0bcR41).

**Comment by niftylettuce** [comment]
thank you very much for the speed with these, it's really nice to hear back so quick and to have your help.  I'm using this for https://github.com/crocodilejs/custom-fonts-in-emails which I'm writing tests for now (the Readme has changed a lot since I pushed initial commit)

**Comment by vutran** [comment]
@niftylettuce That's a pretty cool project you have there. Would be super useful to generate custom buttons. Looking forward to see your module take shape and mature.
